spring.application.name=homework_generator
# Tamanho máximo de CADA arquivo individualmente (ex: 10 Megabytes)
spring.servlet.multipart.max-file-size=10MB

# Tamanho máximo da requisição inteira (soma de todos os arquivos + dados)
spring.servlet.multipart.max-request-size=50MB